-- Insert Sample Lead Records
-- This script inserts sample lead data for testing and development

-- Sample Lead 1: Ryan Beuglet
INSERT INTO leads (
    lead_id,
    first_name,
    last_name,
    full_name,
    email,
    phone,
    date_of_birth,
    address_line1,
    city,
    state_province,
    postal_code,
    country,
    country_code,
    vehicle_type,
    current_credit,
    employment_status,
    job_title,
    company_name,
    monthly_salary_min,
    monthly_salary_max,
    employment_length,
    length_at_company,
    length_at_home_address
) VALUES (
    'HIWCOSE3',
    'Ryan',
    'Beuglet',
    'Ryan Beuglet',
    'renoright1987@gmail.com',
    '(519) 717-4414',
    '1987-05-31',
    '519-17 Bellerive Line',
    'Chatham Kent Rose Lane',
    'Chatham',
    'N7M 5J8',
    'Ontario, Canada',
    'ON',
    'Truck',
    'Self-employed salary',
    'Self-Employed',
    'Owner',
    'Precision Insulation Services',
    3501.00,
    4500.00,
    '2 years+',
    '2 years',
    '2 years+'
);

-- Sample Lead 2: John Smith (Example)
INSERT INTO leads (
    lead_id,
    first_name,
    last_name,
    full_name,
    email,
    phone,
    date_of_birth,
    address_line1,
    address_line2,
    city,
    state_province,
    postal_code,
    country,
    country_code,
    vehicle_type,
    current_credit,
    employment_status,
    job_title,
    company_name,
    monthly_salary_min,
    monthly_salary_max,
    employment_length,
    length_at_company,
    length_at_home_address
) VALUES (
    'LEAD001',
    'John',
    'Smith',
    'John Smith',
    'john.smith@example.com',
    '(416) 555-1234',
    '1985-03-15',
    '123 Main Street',
    'Apt 4B',
    'Toronto',
    'Ontario',
    'M5H 2N2',
    'Ontario, Canada',
    'ON',
    'Car',
    'Employed salary',
    'Employed',
    'Software Engineer',
    'Tech Solutions Inc.',
    5000.00,
    6000.00,
    '3 years+',
    '1 year',
    '1-2 years'
);

-- Sample Lead 3: Sarah Johnson (Example)
INSERT INTO leads (
    lead_id,
    first_name,
    last_name,
    full_name,
    email,
    phone,
    date_of_birth,
    address_line1,
    city,
    state_province,
    postal_code,
    country,
    country_code,
    vehicle_type,
    current_credit,
    employment_status,
    job_title,
    company_name,
    monthly_salary_min,
    monthly_salary_max,
    employment_length,
    length_at_company,
    length_at_home_address
) VALUES (
    'LEAD002',
    'Sarah',
    'Johnson',
    'Sarah Johnson',
    'sarah.johnson@example.com',
    '(514) 555-5678',
    '1990-07-22',
    '456 Oak Avenue',
    'Montreal',
    'Quebec',
    'H3A 1A1',
    'Quebec, Canada',
    'QC',
    'SUV',
    'Employed salary',
    'Employed',
    'Marketing Manager',
    'Digital Marketing Co.',
    4500.00,
    5500.00,
    '2 years+',
    '2 years+',
    '3 years+'
);

-- Sample Lead 4: Michael Chen (Example - Self-Employed)
INSERT INTO leads (
    lead_id,
    first_name,
    last_name,
    full_name,
    email,
    phone,
    date_of_birth,
    address_line1,
    city,
    state_province,
    postal_code,
    country,
    country_code,
    vehicle_type,
    current_credit,
    employment_status,
    job_title,
    company_name,
    monthly_salary_min,
    monthly_salary_max,
    employment_length,
    length_at_company,
    length_at_home_address
) VALUES (
    'LEAD003',
    'Michael',
    'Chen',
    'Michael Chen',
    'michael.chen@example.com',
    '(604) 555-9012',
    '1988-11-08',
    '789 Pine Street',
    'Vancouver',
    'British Columbia',
    'V6B 1A1',
    'British Columbia, Canada',
    'BC',
    'Truck',
    'Self-employed salary',
    'Self-Employed',
    'Business Owner',
    'Chen Construction Ltd.',
    4000.00,
    5000.00,
    '5 years+',
    '5 years+',
    '4 years+'
);

-- Sample Lead 5: Emily Davis (Example - Part-time)
INSERT INTO leads (
    lead_id,
    first_name,
    last_name,
    full_name,
    email,
    phone,
    date_of_birth,
    address_line1,
    city,
    state_province,
    postal_code,
    country,
    country_code,
    vehicle_type,
    current_credit,
    employment_status,
    job_title,
    company_name,
    monthly_salary_min,
    monthly_salary_max,
    employment_length,
    length_at_company,
    length_at_home_address
) VALUES (
    'LEAD004',
    'Emily',
    'Davis',
    'Emily Davis',
    'emily.davis@example.com',
    '(403) 555-3456',
    '1992-02-14',
    '321 Elm Road',
    'Calgary',
    'Alberta',
    'T2P 1M5',
    'Alberta, Canada',
    'AB',
    'Car',
    'Part-time salary',
    'Part-Time',
    'Sales Associate',
    'Retail Store Inc.',
    2000.00,
    2500.00,
    '1-2 years',
    '6 months',
    '1 year'
);

-- Verify the inserts
SELECT 
    lead_id,
    full_name,
    email,
    phone,
    vehicle_type,
    employment_status,
    company_name,
    created_at
FROM leads
ORDER BY created_at DESC;
